config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'pages#home'

  resources :meetings, only: [:index, :show, :edit, :create, :new] do
    resources :agendas, only: [:create]
    resources :tasks, only: [:create]
  end

  resources :attendances, only: [:edit]

  resources :agendas, only: [:edit, :start, :finish, :update]

  post 'meetings/:id/:user_id', to: 'attendances#create', as: :invite_attendance

  put 'meetings/:id/start', to: 'meetings#start', as: :start_meeting

  put 'meetings/:id/finish', to: 'meetings#finish', as: :finish_meeting

  # summary page after meeting
  get 'meetings/:id/summary', to: 'meetings#summary', as: :meeting_summary

  # pdf generating routes
  get 'meetings/:id/report', to: 'meetings#report', as: :meeting_report
end

app/views/shared/_agenda.html.erb
<div class="d-flex justify-content-between align-items-center mt-3">
  <h2 style="font-size: 24px">
    <%= @meeting.title %> |
    <span style="font-size: 20px;"><%= @meeting.date_time.strftime("%A, %d %b %Y at %l:%M %p") %></span><span style="font-style:italic;"><span class="ml-3" style="font-size: 16px; ">
         <%= @meeting.duration%> mins.</span></span></h2>
  <div class="trello-btn">
    <% if @meeting.trello_board == "" %>
      <p>""</p>
    <% else %>
      <%= link_to 'Trello board linked', @meeting.trello_board, target: "_blank", class: "btn btn-secondary mb-2" %>
    <% end %>
  </div>
  <p class="mb-1">Hosted By:
  <% if @meeting.user.photo.attached? %>
    <%= cl_image_tag "#{@meeting.user.photo.key}", alt: "alttext", class: "avatar" %>
    <% else %>
    <%= image_tag "avatar.jpg", alt: "avatar", class: 'avatar dropdown-toggle avatar mx-1',id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% end %>

  </p>
</div>
<div class="agenda-card mt-3">
  <div class="agenda progress-container">
    <!--  <h2 class="mt-1 ml-1">Agenda</h2> -->
    <ol class="row justify-content-center postitul progress-tracker">
      <% i = 0 %>
      <% @meeting.agendas.each do |agenda| %>
        <li class="postit progress-step">
          <div class="progress-marker"><%= i+1 %></div>
          <div class="progress-text"><%= agenda.title %></div>
        </li>
        <% i += 1 %>
      <% end %>
      <% if @meeting.user == current_user %>
        <li class="postitform col-2 m-3 p-1">
          <div class="agenda-form">
            <%= simple_form_for [@meeting, @agenda] do |f| %>
              <div class="agenda-input">
                <%= f.input :title, label: false, placeholder: 'Agenda Item' %>
                <div class="text-center">
                  <%= f.submit 'Create', :class => 'btn btn-primary' %>
                </div>
              </div>
            <% end %>
          </div>
        </li>
      <% end %>
    </ol>
  </div>
  <div class="d-flex justify-content-center">
    <div class="meeting-table" style="background-image: url('<%= asset_path 'table.jpg' %>');">
      <div class="mtgtableattendee">
      <% if @meeting.user.photo.attached? %>
        <%= cl_image_tag "#{@meeting.user.photo.key}", alt: "alttext", class: "avatar-large mx-1 align-self-start" %>
      <% else %>
        <%= image_tag "avatar.jpg", alt: "avatar", class: 'avatar-large mx-1 align-self-start' %>
      <% end %>
      </div>
      <% @meeting.attendances.each do |attendance| %>
        <% if attendance.user.photo.attached? %>
          <div class="mtgtableattendee">
            <%= cl_image_tag "#{attendance.user.photo.key}", alt: "alttext", class: "avatar-large mx-1 align-self-start" %>
          </div>
        <% else %>
          <div class="mtgtableattendee">
            <%= image_tag "avatar.jpg", alt: "avatar", class: 'avatar-large mx-1 align-self-start' %>
          </div>
        <% end %>
      <% end %>
      <% if current_user == @meeting.user %>
        <%= render 'shared/invite' %>
      <% end %>
      <% if @meeting.user == current_user %>
        <div class="meetingstart">
          <%= link_to "Start!", start_meeting_path(@meeting), :method=> :put, id: "start-agenda", class: "btn btn-primary"  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_assigntasks.html.erb
<div class="d-flex justify-content-between align-items-center mt-3">
  <h2 style="font-size: 24px">
    <%= @meeting.title %> |
    <span style="font-size: 20px;"><%= @meeting.date_time.strftime("%A, %d %b %Y at %l:%M %p") %></span><span style="font-style:italic;"><span class="ml-3" style="font-size: 16px; ">
        <%= @meeting.duration%> mins.</span></span></h2>
  <div class="trello-btn">
    <% if @meeting.trello_board == "" %>
       <p>""</p>
    <% else %>
      <%= link_to 'Trello board linked', @meeting.trello_board, target: "_blank", class: "btn btn-secondary mb-2" %>
    <% end %>
  </div>
  <p class="mb-1">Hosted By:
    <%= cl_image_tag "#{@meeting.user.photo.key}", alt: "alttext", class: "avatar" %>
  </p>
</div>

<div class="agenda-card mt-3">

  <div class="agenda progress-container">
    <ol class="row justify-content-center postitul progress-tracker">
      <% i = 0 %>
      <% @meeting.agendas.each do |agenda| %>
        <li id='<%= "agenda#{i}" %>' class="postit progress-step">
          <div class="postit-card d-flex flex-column justify-content-center">
            <div class="progress-marker"><%= i+=1 %></div>
            <div class="progress-text"><%= agenda.title %></div>

            <% if agenda.audio.attached? %>
              <% url = cl_video_path(agenda.audio.key) %>
              <audio controls class="audio" style="width: 100%;">
                <source src="<%= url %>" type="audio/mpeg">
                Your browser does not support the audio tag.
              </audio>
              <% else %>
              <audio controls class="audio" style="width: 100%;">
                <source src="" type="audio/mpeg">
                Your browser does not support the audio tag.
              </audio>
            <% end %>
          </div>
        </li>
      <% end %>
    </ol>
  </div>


  <div class="d-flex justify-content-center">
    <div class="meeting-table" style="background-image: url('<%= asset_path 'table.jpg' %>');">
      <div class="mtgtableattendee">
        <%= cl_image_tag "#{@meeting.user.photo.key}", alt: "alttext", class: "avatar-large mx-1 align-self-start" %>
      </div>
      <% @meeting.attendances.each do |attendance| %>
        <% if attendance.user.photo.attached? %>
          <div class="mtgtableattendee">
            <%= cl_image_tag "#{attendance.user.photo.key}", alt: "alttext", class: "avatar-large mx-1 align-self-start" %>
          </div>
        <% else %>
          <div class="mtgtableattendee">
            <%= image_tag "avatar.jpg", alt: "avatar", class: 'avatar-large mx-1 align-self-start' %>
          </div>
        <% end %>
      <% end %>
        <div class="agenda button-list">
    <div class="heading d-flex justify-content-between">
      <div class="finish-actions">
        <!-- Back to Dashboard -->

        <%= link_to meetings_path, class: "btn btn-primary m-1 fa-1x"  do %>
          <i class="fas fa-door-open"> </i>
        <% end %>
        <!--  pdf generator -->
        <%= link_to meeting_report_path(format: :pdf), target: :_blank, class: "btn btn-primary m-1 fa-1x" do %>
          <i class="fas fa-file-download"></i>
        <% end %>
        <!-- share through email -->
        <% team_email = [] %>
        <% @meeting.attendances.each do |attendance| %>
          <% team_email << attendance.user.email %>
        <% end %>
        <% emails = team_email.join(', ') %>
        <% subject = @meeting.date_time.strftime('%Y%m%d') + '_Minutes: ' + @meeting.title %>
        <% host_email = @meeting.user.email %>
        <% link = "(https://www.syncalyst.com/meetings/#{@meeting.id}/report.pdf)" %>
        <% body =  "Hi all,\nThank you for time in the meeting just now.\n\nThe minutes is ready for this meeting: #{@meeting.title}.\n\nPlease find the PDF document from this link: https://www.syncalyst.com/meetings/#{@meeting.id}/report.pdf.\n\nHave a nice day.\n\n(This is an email generated by Syncalyst.)" %>
        <%= mail_to emails, subject: subject, cc: host_email, body: body, reply_to: host_email, class: 'btn btn-primary m-1 fa-1x' do %>
          <i class="far fa-envelope"></i>
        <% end %>

      </div>
    </div>
  </div>
    </div>
  </div>
</div>
<div id="taskhidden"></div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_invite.html.erb
<div class="mtgtableattendee">
  <button type="button" class="btn btn-lg btn-primary rounded-circle" data-toggle="modal" data-target="#exampleModalLong">
    <i class="fas fa-plus"></i>
  </button>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Invite people to your meeting!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% User.all %>
        <% @meeting.attendances %>
        <ul class="list-group">
          <!-- if there are attendance for the meeting... -->
          <% if @meeting.attendances.any? %>
            <% invited = @meeting.attendances.map(&:user) %>
            <% uninvited = User.all - invited - [current_user] %>
            <% if uninvited.empty? %>
              <p>There are no more people to invite.</p>
            <% else %>
              <% uninvited.each do |user| %>
                <li class="list-group-item list-group-item-action">
                  <div class="avatar-card d-flex align-items-center justify-content-between">
                    <div class="user-name d-flex flex-column justify-content-center align-items-center">
                      <p><%= user.nickname %></p>
                      <% if user.photo.attached? %>
                        <%= cl_image_tag "#{user.photo.key}", alt: "alttext", class: "avatar mx-1 align-self-start" %>
                      <% else %>
                        <%= image_tag "avatar.jpg", alt: "avatar", class: 'avatar mx-1 align-self-start' %>
                      <% end %>
                    </div>
                    <div class="user-bundle d-flex align-items-center">
                      <div class="d-flex flex-column justify-content-start">
                        <p>Jobtitle:</p>
                        <p>Email:</p>
                      </div>
                      <div class="d-flex flex-column justify-content-end">
                        <p><%= user.job_title %></p>
                        <p><%= user.email %></p>
                      </div>
                      <% if false %>
                        <div class="user-info d-flex justify-content-between">
                          <p>Jobtitle:</p>
                          <p><%= user.job_title %></p>
                        </div>
                        <div class="user-info d-flex justify-content-between">
                          <p>email:</p>
                          <p><%= user.email %></p>
                        </div>
                      <% end %>
                    </div>
                    <%= link_to invite_attendance_path(@meeting,user), class: 'btn btn-primary',method: :post, remote: true  do %>
                      <i class="fas fa-user-plus"></i>
                    <% end %>
                  </div>
                </li>
              <% end %>
            <% end %>
          <% else %>
            <!-- if there are no attendances yet... -->
            <% (User.all - [current_user]).each do |user| %>
              <li class="list-group-item list-group-item-action">
                <div class="avatar-card d-flex align-items-center justify-content-between">
                  <div class="user-name d-flex flex-column justify-content-center align-items-center">
                    <p><%= user.nickname %></p>
                    <% if user.photo.attached? %>
                      <%= cl_image_tag "#{user.photo.key}", alt: "alttext", class: "avatar mx-1 align-self-start" %>
                    <% else %>
                      <%= image_tag "avatar.jpg", alt: "avatar", class: 'avatar mx-1 align-self-start' %>
                    <% end %>
                  </div>
                  <div class="user-bundle d-flex flex-column align-items-center">
                    <div class="d-flex flex-column">
                      <p>Jobtitle: <%= user.job_title %></p>
                      <p>email:  <%= user.email %></p>
                    </div>
                  </div>
                  <%= link_to invite_attendance_path(@meeting,user), class: 'btn btn-primary',method: :post, remote: true  do %>
                    <i class="fas fa-user-plus"></i>
                  <% end %>
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_newnavbar.html.erb
<div class='navbar navbar-fixed-top'>
  <nav class='navbar-inner header'>
    <div class="container">
      <div class='brand'>
      <%= link_to root_path do  %>
        <%= image_tag "syncalyst_logo.jpg", :size => "80x40", alt: "logo" %>
      <% end %>

      </div>
      <ul class='nav pull-right'>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle avatar mx-1", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "avatar.jpg", alt: "avatar", class: 'avatar dropdown-toggle avatar mx-1',id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to 'New Meeting', new_meeting_path, class: 'nav-link' %>
              <%= link_to "Dashboard", meetings_path, class: "nav-link"  %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </div>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <div class='triangle-down center'>
        <p>
          <i class='fa fa-chevron-down fa-2x isDown' id='toggle'></i>
        </p>
      </div>
    </div>
  </nav>
  <br>
</div>

app/views/shared/_transcription.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h2 style="font-size: 24px">

    <%= @meeting.title %> |
    <span style="font-size: 20px;"><%= @meeting.date_time.strftime("%A, %d %b %Y at %l:%M %p") %></span><span style="font-style:italic;"><span class="ml-3" style="font-size: 16px; ">
        <%= @meeting.duration%> mins.</span></span></h2>
  <div class="trello-btn">
    <% if @meeting.trello_board == "" %>
      <p>""</p>
    <% else %>
      <%= link_to 'Trello board linked', @meeting.trello_board, target: "_blank", class: "btn btn-secondary mb-2" %>
    <% end %>
  </div>
  <p class="mb-1">Hosted By:
    <%= cl_image_tag "#{@meeting.user.photo.key}", alt: "alttext", class: "avatar" %>
  </p>
</div>
<div class="agenda-card mt-3">
  <div class="progress-container">
    <ol class="progress-tracker">
      <% i = 0 %>
      <% @meeting.agendas.each do |agenda| %>
        <li id='<%= "agenda#{i}" %>' data-agenda="<%= agenda.id %>" class=" postit postit-pointer progress-step">
          <!-- add .is-complete if the agenda is finished -->
          <!-- add .is-active on the current agenda -->
          <div class="progress-marker"><%= i+1 %></div>
          <div class="progress-text"><%= agenda.title %></div>
          <!-- remove .count and add .checkmark if the agenda is finished -->
        </li>
        <% i += 1 %>
      <% end %>
    </ol>
  </div>
  <div class="d-flex justify-content-center">
    <div class="meeting-table" style="background-image: url('<%= asset_path 'table.jpg' %>');">
      <div data-userid="<%= @meeting.user.id %>" class="mtgtableattendee task-owner">
        <%= cl_image_tag "#{@meeting.user.photo.key}", :data => { :userid => @meeting.user.id }, alt: "alttext", class: "task-avatar avatar-large mx-1 align-self-start" %>
        <div data-userid="<%= @meeting.user.id %>" class="task-form">
          <%= simple_form_for([@meeting, @task]) do |f| %>
            <%= f.input :user_id, label: false , :input_html => { :value => @meeting.user.id, "data-trelloid" => @meeting.user.trello_member_id, "data-meeting" => @meeting.title, :type => 'hidden' } %>
            <%= f.input :description, label: false, class: "task-description" %>
            <%= f.submit %>
          <% end %>
        </div>
      </div>
      <% @meeting.attendances.each do |attendance| %>
        <% if attendance.user.photo.attached? %>
          <div data-userid="<%= attendance.user.id %>" class="mtgtableattendee task-owner">
            <%= cl_image_tag "#{attendance.user.photo.key}", alt: "alttext", class: "task-avatar avatar-large mx-1 align-self-start", :data => { :userid => attendance.user.id } %>
            <div data-userid="<%= attendance.user.id %>" class="task-form">
              <%= simple_form_for([@meeting, @task]) do |f| %>
                <%= f.input :user_id, label: false , :input_html => { :value => attendance.user.id, "data-trelloid" => attendance.user.trello_member_id, "data-meeting" => attendance.meeting.title, :type => 'hidden' } %>
                <%= f.input :description, label: false, class: "task-description" %>
                <%= f.submit %>
              <% end %>
            </div>
          </div>
        <% else %>
          <div data-userid="<%= attendance.user.id %>" class="mtgtableattendee task-owner">
            <%= image_tag "avatar.jpg", alt: "avatar", class: 'task-avatar avatar-large mx-1 align-self-start', :data => { :userid => attendance.user.id } %>
            <div data-userid="<%= attendance.user.id %>" class="task-form">
              <%= simple_form_for([@meeting, @task]) do |f| %>
                <%= f.input :user_id, label: false , :input_html => { :value => attendance.user.id, "data-trelloid" => attendance.user.trello_member_id, "data-meeting" => attendance.meeting.title, :type => 'hidden' } %>
                <%= f.input :description, label: false, class: "task-description" %>
                <%= f.submit %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
      <div class="currentagendaitem" id="currentpostit">
      </div>
      <div class="meetingend">
        <% if @meeting.user == current_user %>
          <div class="d-flex justify-content-center">
            <%= link_to "Finish", finish_meeting_path(@meeting), :method=> :put, id: "wrap-up", class: "btn btn-primary"  %>
          </div>
        <% end %>
      </div>
      <div class="d-flex justify-content-center cheatsheet">
        <div class="inprogress-card mt-4">
          <h5>Voice Commands</h5>
          <p>Use the following commands to progress through the meeting:</p>
          <ul>
            <li>"First on the Agenda"</li>
            <li>"Stop"</li>
            <li>"Next on the Agenda"</li>
            <li>"Can you (task to assign)?"</li>
            <li>"Show Transcript"</li>
            <li>"Hide Transcript"</li>
            <li>"Order Coffee"</li>
          </ul>
        </div>
      </div>
      <div class="d-flex justify-content-center meetingtranscript">
        <div class="inprogress-card mt-4">
          <div class="d-flex justify-content-between">
            <div id="record" class="record-hidden"><i class="fa fa-circle text-danger"></i>&nbsp; Recording </div>
          </div>
          <% @meeting.agendas.each do |agenda| %>
            <div data-agenda="<%= agenda.id %>" class="transcription transcription-display">
              <!-- form dynamically generated by JS -->
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <button class="record btn-primary btn btn-xs" style="display:none">Record</button>
    <button class="stopRecording btn-warning btn btn-xs" style="display: none">stop</button>
    <div class="sound-clips">
    </div>
  </div>
</div>